/*
Autor:Missael Hernandez Rosado
Fecha de creación: 07/05/2016
Fecha de Modificación:09/05/2016
Descripción: Esta clase define la interfaz para el modulo de prestamo. Como el 
    prestamo requiere de precondición que este logueado el usuario bibliotecario,
    esto se omite en la coprobación y se usa uno ficticio.
*/

package Interfaz;

import Excepciones.ErrorConexionBaseDatosException;
import Excepciones.ObjetoNoEncontradoException;
import Excepciones.PrestatarioSinPrestamosDisponiblesException;
import Excepciones.RegistroMalFormadoException;
import accesodatos.dao.PrestamoDAO;
import accesodatos.dao.PrestatarioDAO;
import accesodatos.dao.impl.PrestamoDAOImpl;
import accesodatos.dao.impl.PrestatarioDAOImpl;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;

/**
 *
 * @author missael
 */
public class Prestamo extends javax.swing.JFrame {

    /**
     * Creates new form Prestamo
     */
    public Prestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
        prestamo = new PrestamoDAOImpl();
        this.idPersonalPredefinido = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbMatriculaPrestatario = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtClaveEjemplar = new javax.swing.JTextField();
        lbClaveEjemplar = new javax.swing.JLabel();
        btnSolicitarPrestamo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solicitar prestamo");
        setResizable(false);

        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Prestamos");

        lbMatriculaPrestatario.setText("Matricula del prestatario");

        txtMatricula.setToolTipText("Ej: S1");
        txtMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatriculaFocusLost(evt);
            }
        });
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        txtClaveEjemplar.setToolTipText("Ej: EJ1-1");
        txtClaveEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveEjemplarActionPerformed(evt);
            }
        });

        lbClaveEjemplar.setText("Clave del ejemplar");

        btnSolicitarPrestamo.setText("Solicitar prestamo");
        btnSolicitarPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitarPrestamoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbClaveEjemplar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtClaveEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMatriculaPrestatario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnSolicitarPrestamo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbTitulo)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMatriculaPrestatario)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClaveEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbClaveEjemplar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnSolicitarPrestamo)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtClaveEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveEjemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveEjemplarActionPerformed

    private void txtMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatriculaFocusLost

        
        boolean matriculaValida = false;
        try {
            int idPrestatario = getIdPorMatricula(this.txtMatricula.getText());
            matriculaValida = prestamo.verificarPrestatario(idPrestatario);
        } catch (ObjetoNoEncontradoException ex) {
            JOptionPane.showMessageDialog(this, "La matricula no fue encontrada en a base de datos, intente de nuevo", "Objeto no encontrado", JOptionPane.WARNING_MESSAGE);
        } catch (ErrorConexionBaseDatosException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un problema en la conexión a la base de datos", "Error en la conexión", JOptionPane.ERROR_MESSAGE);
        }
        if(!matriculaValida){
            this.txtMatricula.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED, Color.RED, Color.RED));
        } else {
            this.txtMatricula.setBorder(null);
        }
        
    }//GEN-LAST:event_txtMatriculaFocusLost

    private void btnSolicitarPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarPrestamoMouseClicked
        // TODO add your handling code here:
        int idPrestatario;
        int idBibliotecario;
        String idEjemplar;
        boolean seRegistroConExito = false;
        try {
            idPrestatario = getIdPorMatricula(this.txtMatricula.getText());
            idBibliotecario = getIdBibliotecario();
            idEjemplar = this.txtClaveEjemplar.getText();
            seRegistroConExito = prestamo.RegistrarNuevoPrestamo(idPrestatario, idBibliotecario, idEjemplar);
        } catch (ObjetoNoEncontradoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Objeto no encontrado", JOptionPane.ERROR_MESSAGE);
        } catch (ErrorConexionBaseDatosException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un problema en la conexión a la base de datos", "Error en la conexión", JOptionPane.ERROR_MESSAGE);
        } catch (RegistroMalFormadoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Revise los campos de texto y vuelva intentarlo", JOptionPane.WARNING_MESSAGE);
        } catch (PrestatarioSinPrestamosDisponiblesException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Sin prestamos disponibles para el usuario", JOptionPane.WARNING_MESSAGE);
        }
        if(seRegistroConExito){
            JOptionPane.showMessageDialog(this, "Prestamo autorizado", "Prestamo registrado", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSolicitarPrestamoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Prestamo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolicitarPrestamo;
    private javax.swing.JLabel lbClaveEjemplar;
    private javax.swing.JLabel lbMatriculaPrestatario;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtClaveEjemplar;
    private javax.swing.JTextField txtMatricula;
    // End of variables declaration//GEN-END:variables

    //variables de misa :P
    PrestamoDAO prestamo;
    int idPersonalPredefinido;
    
    
    //funciones por misa
    private int getIdPorMatricula(String matricula) throws ObjetoNoEncontradoException, ErrorConexionBaseDatosException{
        PrestatarioDAO prestatario = new PrestatarioDAOImpl();
        return prestatario.getIdentificadorPorNumeroPersonal(matricula);
    }
    private int getIdBibliotecario(){
        return this.idPersonalPredefinido;
    }
}
