-- MySQL Script generated by MySQL Workbench
-- Sat May 21 12:39:25 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TBTiposPersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBTiposPersonal` (
  `idTipo` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idTipo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TBPersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBPersonal` (
  `idPersonal` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `numeroPersonal` VARCHAR(50) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `direccion` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `fechaNacimiento` DATE NULL DEFAULT NULL COMMENT '',
  `tipo` INT UNSIGNED NOT NULL COMMENT '',
  `telefono` VARCHAR(15) NULL DEFAULT NULL COMMENT '',
  `correo` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `creadoEn` DATETIME NULL COMMENT '',
  `actualizadoEn` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idPersonal`)  COMMENT '',
  CONSTRAINT `tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `mydb`.`TBTiposPersonal` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBTiposPrestatarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBTiposPrestatarios` (
  `idTipoPrestatario` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`idTipoPrestatario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TBPrestatarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBPrestatarios` (
  `idPrestatario` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `numeroPersonal` VARCHAR(50) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `direccion` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `fechaNacimiento` DATE NULL DEFAULT NULL COMMENT '',
  `tipo` INT UNSIGNED NOT NULL COMMENT '',
  `telefono` VARCHAR(15) NULL DEFAULT NULL COMMENT '',
  `correo` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `vigencia` DATE NOT NULL COMMENT '',
  `creadoEn` DATETIME NULL COMMENT '',
  `actualizadoEn` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idPrestatario`)  COMMENT '',
  CONSTRAINT `tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `mydb`.`TBTiposPrestatarios` (`idTipoPrestatario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBPrestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBPrestamos` (
  `idPrestamo` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `fechaVencimiento` DATETIME NOT NULL COMMENT '',
  `fechaSolicitudPrestamo` DATETIME NOT NULL COMMENT '',
  `fechaEntrega` DATETIME NULL COMMENT '',
  `idPersonal` INT UNSIGNED NOT NULL COMMENT '',
  `idPrestatario` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`idPrestamo`)  COMMENT '',
  CONSTRAINT `idPersonal`
    FOREIGN KEY (`idPersonal`)
    REFERENCES `mydb`.`TBPersonal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPrestatario`
    FOREIGN KEY (`idPrestatario`)
    REFERENCES `mydb`.`TBPrestatarios` (`idPrestatario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBTiposMonedas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBTiposMonedas` (
  `idTipo` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTipo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TBAdeudos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBAdeudos` (
  `idAdeudo` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `fechaInicial` DATETIME NOT NULL COMMENT '',
  `fechaFinal` DATETIME NULL COMMENT '',
  `monto` DECIMAL(2) NULL DEFAULT NULL COMMENT '',
  `idMonedaAdeudo` INT UNSIGNED NULL COMMENT '',
  `tipo` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `idPrestamo` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idAdeudo`)  COMMENT '',
  CONSTRAINT `idPrestamo`
    FOREIGN KEY (`idPrestamo` , `idMonedaAdeudo`)
    REFERENCES `mydb`.`TBPrestamos` (`idPrestamo` , `idPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idMonedaAdeudo`
    FOREIGN KEY ()
    REFERENCES `mydb`.`TBTiposMonedas` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBTiposDonadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBTiposDonadores` (
  `idTipo` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTipo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TBDonadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBDonadores` (
  `idDonador` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `correo` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `direccion` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `telefono` VARCHAR(15) NULL DEFAULT NULL COMMENT '',
  `tipo` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`idDonador`)  COMMENT '',
  CONSTRAINT `tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `mydb`.`TBTiposDonadores` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBDonaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBDonaciones` (
  `idDonacion` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATE NULL DEFAULT NULL COMMENT '',
  `esMonetario` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `donador` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idDonacion`)  COMMENT '',
  CONSTRAINT `donador`
    FOREIGN KEY (`donador`)
    REFERENCES `mydb`.`TBDonadores` (`idDonador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBAdquisiciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBAdquisiciones` (
  `idAdquisicion` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATETIME NOT NULL COMMENT '',
  `fueDonado` TINYINT(1) NOT NULL COMMENT '',
  `idDonacion` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idAdquisicion`)  COMMENT '',
  CONSTRAINT `idDonacion`
    FOREIGN KEY (`idDonacion`)
    REFERENCES `mydb`.`TBDonaciones` (`idDonacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBCondonaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBCondonaciones` (
  `idAdeudo` INT(11) NOT NULL COMMENT '',
  `autoridad` INT UNSIGNED NOT NULL COMMENT '',
  `justificacion` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`idAdeudo`)  COMMENT '',
  INDEX `idAdeudo_idx` (`idAdeudo` ASC)  COMMENT '',
  UNIQUE INDEX `idAdeudo_UNIQUE` (`idAdeudo` ASC)  COMMENT '',
  CONSTRAINT `idAdeudo`
    FOREIGN KEY (`idAdeudo`)
    REFERENCES `mydb`.`TBAdeudos` (`idAdeudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `autoridad`
    FOREIGN KEY (`autoridad`)
    REFERENCES `mydb`.`TBPersonal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBTiposMultimedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBTiposMultimedia` (
  `idTipo` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idTipo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TBMultimedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBMultimedia` (
  `idMultimedia` VARCHAR(50) NOT NULL COMMENT '',
  `tipo` INT UNSIGNED NOT NULL COMMENT '',
  `titulo` VARCHAR(45) NOT NULL COMMENT '',
  `areaEducativa` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `narrador` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `nombreDelLibro` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `plataforma` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `version` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `año` DATE NULL DEFAULT NULL COMMENT '',
  `director` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `creadoEn` DATETIME NULL COMMENT '',
  `actualizadoEn` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idMultimedia`)  COMMENT '',
  CONSTRAINT `tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `mydb`.`TBTiposMultimedia` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBReportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBReportes` (
  `idReporte` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `fechaInicio` DATE NULL DEFAULT NULL COMMENT '',
  `fechaFinal` DATE NULL DEFAULT NULL COMMENT '',
  `tipo` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `rutaArchivo` VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idReporte`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBTiposTextos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBTiposTextos` (
  `idTipo` INT UNSIGNED NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idTipo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TBEditoriales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBEditoriales` (
  `idEditorial` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idEditorial`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TBTextos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBTextos` (
  `idTexto` VARCHAR(50) NOT NULL COMMENT '',
  `tipo` INT UNSIGNED NOT NULL COMMENT '',
  `titulo` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `editorial` INT UNSIGNED NOT NULL COMMENT '',
  `fechaDePublicacion` DATE NULL DEFAULT NULL COMMENT '',
  `numeroDePaginas` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `numeroDePublicacion` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `lugarDePublicacion` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `numeroDeRevista` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `creadoEn` DATETIME NULL COMMENT '',
  `modificadoEn` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idTexto`)  COMMENT '',
  CONSTRAINT `tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `mydb`.`TBTiposTextos` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `editorial`
    FOREIGN KEY (`editorial`)
    REFERENCES `mydb`.`TBEditoriales` (`idEditorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBTextoEjemplares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBTextoEjemplares` (
  `idEjemplar` VARCHAR(50) NOT NULL COMMENT '',
  `idTexto` VARCHAR(50) NOT NULL COMMENT '',
  `idAdquisicion` INT(11) UNSIGNED NOT NULL COMMENT '',
  `disponible` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`idEjemplar`)  COMMENT '',
  CONSTRAINT `idTexto`
    FOREIGN KEY (`idTexto`)
    REFERENCES `mydb`.`TBTextos` (`idTexto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idAdquisicion`
    FOREIGN KEY (`idAdquisicion`)
    REFERENCES `mydb`.`TBAdquisiciones` (`idAdquisicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBReservaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBReservaciones` (
  `idReservacion` INT(11) UNSIGNED NOT NULL COMMENT '',
  `idTextoEjemplar` VARCHAR(50) NOT NULL COMMENT '',
  `fechaVencimiento` DATETIME NULL DEFAULT NULL COMMENT '',
  `idPrestatario` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`idReservacion`)  COMMENT '',
  CONSTRAINT `idPrestatario`
    FOREIGN KEY (`idPrestatario`)
    REFERENCES `mydb`.`TBPrestatarios` (`idPrestatario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTextoEjemplar`
    FOREIGN KEY (`idTextoEjemplar`)
    REFERENCES `mydb`.`TBTextoEjemplares` (`idEjemplar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`TBAutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBAutores` (
  `idAutor` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`idAutor`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`textos-autores-aux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`textos-autores-aux` (
  `idTexto` VARCHAR(50) NOT NULL COMMENT '',
  `idAutor` INT UNSIGNED NOT NULL COMMENT '',
  CONSTRAINT `idTexto`
    FOREIGN KEY (`idTexto`)
    REFERENCES `mydb`.`TBTextos` (`idTexto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idAutor`
    FOREIGN KEY (`idAutor`)
    REFERENCES `mydb`.`TBAutores` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TBPaises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBPaises` (
  `idPais` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idPais`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`textos-paises-aux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`textos-paises-aux` (
  `idTexto` VARCHAR(50) NOT NULL COMMENT '',
  `idPais` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`idTexto`)  COMMENT '',
  CONSTRAINT `idTexto`
    FOREIGN KEY (`idTexto`)
    REFERENCES `mydb`.`TBTextos` (`idTexto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPais`
    FOREIGN KEY (`idPais`)
    REFERENCES `mydb`.`TBPaises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TBMultimediaEjemplares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBMultimediaEjemplares` (
  `idEjemplar` VARCHAR(50) NOT NULL COMMENT '',
  `idMultimedia` VARCHAR(50) NOT NULL COMMENT '',
  `idAdquision` INT(11) NOT NULL COMMENT '',
  `disponible` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`idEjemplar`)  COMMENT '',
  CONSTRAINT `idMultimedia`
    FOREIGN KEY (`idMultimedia`)
    REFERENCES `mydb`.`TBMultimedia` (`idMultimedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAdquisicion`
    FOREIGN KEY (`idAdquision`)
    REFERENCES `mydb`.`TBAdquisiciones` (`idAdquisicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
